import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  isRTL: boolean;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('thinkpost-language');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('thinkpost-language', language);
    
    // Update document direction and lang attribute
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    
    // Add/remove RTL class for additional styling
    if (isRTL) {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
  }, [language, isRTL]);

  // Enhanced translation function with parameter support
  const t = (key: string, params?: Record<string, any>): string => {
    const translations = getTranslations();
    let translation = translations[language]?.[key] || key;
    
    // Replace parameters in translation if provided
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    
    return translation;
  };

  const value = {
    language,
    setLanguage,
    isRTL,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Comprehensive translations
const getTranslations = () => {
  return {
    en: {
      // Header
      'nav.features': 'Features',
      'nav.howItWorks': 'How It Works',
      'nav.pricing': 'Pricing',
      'nav.contact': 'Contact',
      'header.getStarted': 'Get Started',
      'header.signOut': 'Sign Out',
      'header.welcomeBack': 'Welcome back!',
      
      // Hero
      'hero.badge': 'AI-Powered Content Generation',
      'hero.title.transform': 'Transform Your',
      'hero.title.contentStrategy': 'Content Strategy',
      'hero.subtitle': 'Post smarter. Reach further. AI will do.',
      'hero.description': 'Create engaging, high-quality content in seconds with our advanced AI platform. Boost your productivity and never run out of ideas again.',
      'hero.startCreating': 'Start Creating Free',
      'hero.watchDemo': 'Watch Demo',
      'hero.goToDashboard': 'Go to Dashboard',
      'hero.loading': 'Loading...',
      'hero.demoTitle': 'Demo Video Coming Soon',
      'hero.demoDescription': 'See our AI in action',
      
      // Features
      'features.title.powerful': 'Powerful Features for',
      'features.title.creators': 'Content Creators',
      'features.description': 'Everything you need to create, optimize, and scale your content strategy with the power of AI.',
      'features.feature1.title': 'AI-Powered Generation',
      'features.feature1.description': 'Advanced algorithms create human-like content tailored to your brand voice and style.',
      'features.feature2.title': 'Lightning Fast',
      'features.feature2.description': 'Generate high-quality content in seconds, not hours. Boost your productivity instantly.',
      'features.feature3.title': 'Targeted Content',
      'features.feature3.description': 'Create content optimized for your specific audience and marketing goals.',
      'features.feature4.title': 'Quality Assurance',
      'features.feature4.description': 'Built-in quality checks ensure your content meets the highest standards.',
      'features.feature5.title': 'Multi-Language',
      'features.feature5.description': 'Generate content in over 50 languages to reach a global audience.',
      'features.feature6.title': 'SEO Optimized',
      'features.feature6.description': 'Content automatically optimized for search engines to boost your rankings.',
      
      // How It Works
      'howItWorks.title': 'How It Works',
      'howItWorks.description': 'Get started with ThinkPost in just three simple steps and transform your content creation process.',
      'howItWorks.step1.title': 'Upload Your Products',
      'howItWorks.step1.description': 'Add your product photo and name with a simple upload.',
      'howItWorks.step2.title': 'AI Generates Content',
      'howItWorks.step2.description': 'Our advanced AI creates high-quality, engaging content for each product.',
      'howItWorks.step3.title': 'Review and Publish',
      'howItWorks.step3.description': 'Review the generated content, make any edits, then schedule and publish it across your channels.',
      'howItWorks.startTrial': 'Start Your Free Trial',

      // Pricing
      'pricing.title': 'Simple, Transparent Pricing',
      'pricing.subtitle': 'Choose the perfect plan for your business. All plans include our core AI features.',
      'pricing.mostPopular': 'Most Popular',
      'pricing.plans.free.name': 'Free',
      'pricing.plans.free.period': '/month',
      'pricing.plans.free.description': 'Perfect for getting started',
      'pricing.plans.free.features.posts': '5 posts per month',
      'pricing.plans.free.features.captions': 'Basic AI captions',
      'pricing.plans.free.features.platforms': '2 social platforms',
      'pricing.plans.free.features.support': 'Standard support',
      'pricing.plans.free.features.templates': 'Basic templates',
      'pricing.plans.free.buttonText': 'Start Free',
      'pricing.plans.pro.name': 'Pro',
      'pricing.plans.pro.period': '/month',
      'pricing.plans.pro.description': 'Best for growing businesses',
      'pricing.plans.pro.features.posts': '100 posts per month',
      'pricing.plans.pro.features.captions': 'Advanced AI captions',
      'pricing.plans.pro.features.platforms': 'All social platforms',
      'pricing.plans.pro.features.support': 'Priority support',
      'pricing.plans.pro.features.templates': 'Custom templates',
      'pricing.plans.pro.features.analytics': 'Analytics dashboard',
      'pricing.plans.pro.features.scheduling': 'Scheduling tools',
      'pricing.plans.pro.features.arabic': 'Arabic dialect support',
      'pricing.plans.pro.buttonText': 'Start Pro',
      'pricing.plans.business.name': 'Business',
      'pricing.plans.business.period': '/month',
      'pricing.plans.business.description': 'For large teams and agencies',
      'pricing.plans.business.features.posts': 'Unlimited posts',
      'pricing.plans.business.features.captions': 'Premium AI captions',
      'pricing.plans.business.features.platforms': 'All social platforms',
      'pricing.plans.business.features.support': '24/7 dedicated support',
      'pricing.plans.business.features.branding': 'Custom branding',
      'pricing.plans.business.features.analytics': 'Advanced analytics',
      'pricing.plans.business.features.collaboration': 'Team collaboration',
      'pricing.plans.business.features.api': 'API access',
      'pricing.plans.business.features.whiteLabel': 'White-label solution',
      'pricing.plans.business.features.integrations': 'Custom integrations',
      'pricing.plans.business.buttonText': 'Start Business',
      'pricing.enterprise.title': 'Need Something Custom?',
      'pricing.enterprise.description': 'For enterprise clients with special requirements, we offer custom solutions and dedicated support.',
      'pricing.enterprise.buttonText': 'Contact Sales',

      // FAQ
      'faq.title': 'Frequently Asked Questions',
      'faq.subtitle': 'Everything you need to know about ThinkPost',
      'faq.questions.q1.question': 'How does ThinkPost generate captions?',
      'faq.questions.q1.answer': 'Our advanced AI analyzes your content, understands the context, and generates engaging captions tailored to each social media platform. It considers factors like audience, tone, trending hashtags, and platform-specific best practices.',
      'faq.questions.q2.question': 'Which social media platforms are supported?',
      'faq.questions.q2.answer': 'Currently, we support TikTok — and we\'re actively working to expand support to Instagram, Snapchat, and X (Twitter). Our goal is to deliver optimized, platform-specific content across all major social channels.',
      'faq.questions.q3.question': 'Can I customize the generated captions?',
      'faq.questions.q3.answer': 'Absolutely! Our AI provides a great starting point, but you have full control to edit, modify, or completely rewrite any generated content. You can also set preferences for tone, style, and specific keywords.',
      'faq.questions.q4.question': 'How accurate is the Arabic dialect support?',
      'faq.questions.q4.answer': 'Our AI is designed to create content that fits Saudi culture — capturing local expressions, tone, and relevance to engage Arabic-speaking audiences effectively.',
      'faq.questions.q5.question': 'Is there a free trial available?',
      'faq.questions.q5.answer': 'Yes! Our Free plan gives you 14 AI-generated TikTok posts each month. You can upgrade anytime to unlock more features and scale your content strategy.',
      'faq.questions.q6.question': 'Can I schedule posts for later?',
      'faq.questions.q6.answer': 'Yes, with our Pro and Business plans, you get access to our scheduling tools. You can plan your content calendar and automatically publish posts at optimal times for maximum engagement.',
      'faq.questions.q7.question': 'What file formats do you support?',
      'faq.questions.q7.answer': 'We currently support major image formats like JPG, PNG, GIF, and WebP. Video uploads are not yet supported — but they\'re coming soon!',
      'faq.questions.q8.question': 'How secure is my content?',
      'faq.questions.q8.answer': 'We take security seriously. All uploads are encrypted, and we never store your content longer than necessary.',
      'faq.contact.title': 'Still Have Questions?',
      'faq.contact.description': 'Our support team is here to help you get the most out of ThinkPost',
      'faq.contact.buttonText': 'Contact Support',

      // Footer
      'footer.newsletter.title': 'Stay Updated with ThinkPost',
      'footer.newsletter.description': 'Get the latest updates, tips, and exclusive content creation strategies delivered to your inbox.',
      'footer.newsletter.placeholder': 'Enter your email',
      'footer.newsletter.buttonText': 'Subscribe',
      'footer.description': 'Revolutionizing content creation with AI-powered tools that help you create engaging, high-quality content in seconds.',
      'footer.sections.product': 'Product',
      'footer.sections.company': 'Company',
      'footer.sections.support': 'Support',
      'footer.sections.legal': 'Legal',
      'footer.product.features': 'Features',
      'footer.product.pricing': 'Pricing',
      'footer.product.api': 'API',
      'footer.product.documentation': 'Documentation',
      'footer.company.about': 'About Us',
      'footer.company.careers': 'Careers',
      'footer.company.press': 'Press',
      'footer.company.contact': 'Contact',
      'footer.support.helpCenter': 'Help Center',
      'footer.support.community': 'Community',
      'footer.support.status': 'Status',
      'footer.support.security': 'Security',
      'footer.legal.privacy': 'Privacy Policy',
      'footer.legal.terms': 'Terms of Service',
      'footer.legal.cookies': 'Cookie Policy',
      'footer.legal.gdpr': 'GDPR',
      'footer.copyright': '© 2024 ThinkPost. All rights reserved.',
      'footer.bottomLinks.privacy': 'Privacy',
      'footer.bottomLinks.terms': 'Terms',
      'footer.bottomLinks.cookies': 'Cookies',
      
      // Dashboard
      'dashboard.loading': 'Loading your dashboard...',
      'dashboard.tabs.overview': 'Overview',
      'dashboard.tabs.media': 'Media',
      'dashboard.tabs.captions': 'Captions',
      'dashboard.tabs.schedule': 'Schedule',
      'dashboard.tabs.statistics': 'Statistics',
      
      // Overview Cards
      'dashboard.overview.totalPosts': 'Total Posts',
      'dashboard.overview.totalPostsSubtext': '+12% from last month',
      'dashboard.overview.upcomingPosts': 'Upcoming Posts',
      'dashboard.overview.upcomingPostsSubtext': 'Scheduled this week',
      'dashboard.overview.captionCredits': 'Caption Credits',
      'dashboard.overview.captionCreditsSubtext': '{credits} credits remaining',
      'dashboard.overview.mediaLibrary': 'Media Library',
      'dashboard.overview.mediaLibrarySubtext': 'Images uploaded',
      
      // Quick Actions
      'dashboard.quickActions.title': 'Quick Actions',
      'dashboard.quickActions.addProducts': 'Start & add products',
      'dashboard.quickActions.viewCaptions': 'View Captions',
      'dashboard.quickActions.schedulePost': 'Schedule Post',
      'dashboard.quickActions.workflow': 'Complete workflow: Add content → Generate captions → Schedule posts',
      
      // TikTok Connection
      'dashboard.tiktok.title': 'TikTok Connection',
      'dashboard.tiktok.description': 'Connect your TikTok account to schedule and post content directly',
      'dashboard.tiktok.connectedAs': 'Connected as @{username}',
      'dashboard.tiktok.connectedStatus': 'Connected to TikTok',
      'dashboard.tiktok.disconnect': 'Disconnect TikTok',
      'dashboard.tiktok.connectDescription': 'Connect your TikTok account to access additional features and enhance your content creation.',
      'dashboard.tiktok.connecting': 'Connecting...',
      'dashboard.tiktok.connect': 'Connect TikTok',
      'dashboard.tiktok.readyToConnect': 'Ready to connect',
      
      // Instagram Connection
      'dashboard.instagram.title': 'Instagram Business',
      'dashboard.instagram.description': 'Connect your Instagram Business account to schedule and post content directly',
      'dashboard.instagram.connectedAs': 'Connected as @{username}',
      'dashboard.instagram.connectedStatus': 'Connected',
      'dashboard.instagram.disconnect': 'Disconnect',
      'dashboard.instagram.connectDescription': 'Connect your Instagram Business account to access additional features and enhance your content creation.',
      'dashboard.instagram.connecting': 'Connecting...',
      'dashboard.instagram.connect': 'Connect Instagram Business',
      'dashboard.instagram.readyToConnect': 'Ready to connect',
      
      // User Profile
      'dashboard.profile.owner': 'Owner',
      'dashboard.profile.ownerOf': 'Owner of {name}',
      'dashboard.profile.profileSettings': 'Profile Settings',
      'dashboard.profile.accountSettings': 'Account Settings',
      'dashboard.profile.signOut': 'Sign Out',

      // Profile Settings
      'profileSettings.title': 'Profile Settings',
      'profileSettings.description': 'Update your personal and brand information',
      'profileSettings.personalInfo.title': 'Personal Information',
      'profileSettings.personalInfo.description': 'Manage your personal account details',
      'profileSettings.brandInfo.title': 'Brand Information',
      'profileSettings.brandInfo.description': 'Update your restaurant details and vision',

      // Profile Form
      'profileForm.avatarUrl': 'Avatar URL',
      'profileForm.avatarUrlPlaceholder': 'https://example.com/avatar.jpg',
      'profileForm.email': 'Email',
      'profileForm.fullName': 'Full Name',
      'profileForm.fullNamePlaceholder': 'Enter your full name',
      'profileForm.displayName': 'Display Name',
      'profileForm.displayNamePlaceholder': 'Enter your display name',
      'profileForm.updateProfile': 'Update Profile',
      'profileForm.updating': 'Updating...',
      'profileForm.success': 'Profile Updated',
      'profileForm.successDescription': 'Your profile information has been updated successfully.',
      'profileForm.error': 'Error',
      'profileForm.errorDescription': 'Failed to update profile information.',

      // Restaurant Form
      'restaurantForm.specifyLocation': 'Specify your location',
      'restaurantForm.brandType': 'Brand Type',
      'restaurantForm.selectBrandType': 'Select brand type',
      'restaurantForm.customBrandType': 'Please write your Brand type',
      'restaurantForm.enterBrandType': 'Enter your brand type',
      'restaurantForm.customCategory': 'Please write your restaurant category',
      'restaurantForm.enterCategory': 'Enter your restaurant category',

      // Brand Types
      'brandTypes.restaurant': 'Restaurant',
      'brandTypes.coffee': 'Coffee',
      'brandTypes.bakery': 'Bakery',
      'brandTypes.other': 'Other',

      // Categories
      'categories.fastFood': 'Fast Food',
      'categories.casualDining': 'Casual Dining',
      'categories.fineDining': 'Fine Dining',
      'categories.middleEastern': 'Middle Eastern',
      'categories.asian': 'Asian',
      'categories.italian': 'Italian',
      'categories.american': 'American',
      'categories.mexican': 'Mexican',
      'categories.indian': 'Indian',
      'categories.seafood': 'Seafood',
      'categories.pizza': 'Pizza',
      'categories.coffeeShop': 'Coffee Shop',
      'categories.bakery': 'Bakery',
      'categories.other': 'Other',

      // TikTok Connection
      'tiktok.processing': 'Processing TikTok Connection...',
      'tiktok.pleaseWait': 'Please wait while we complete your TikTok login.',
      'tiktok.connected': 'TikTok Connected!',
      'tiktok.connectedDescription': 'Your TikTok account has been connected successfully.',
      'tiktok.connectedSuccessfully': 'TikTok Connected Successfully!',
      'tiktok.connectionFailed': 'TikTok Connection Failed',
      'tiktok.connectionError': 'There was an error connecting your TikTok account.',
      'tiktok.redirecting': 'Redirecting to your dashboard...',
      'tiktok.errors.general': 'There was an error connecting your TikTok account.',
      'tiktok.errors.missingParameters': 'Missing required parameters from TikTok.',
      'tiktok.errors.invalidState': 'Invalid or expired authorization state.',
      'tiktok.errors.tokenExchangeFailed': 'Failed to exchange authorization code for access token.',
      'tiktok.errors.invalidTokenResponse': 'Invalid response from TikTok\'s token service.',
      'tiktok.errors.profileUpdateFailed': 'Failed to update your profile with TikTok information.',
      'tiktok.errors.internalError': 'An internal error occurred during the connection process.',

      // Brand Setup
      'brandSetup.infoTitle': 'Create High-Quality Content',
      'brandSetup.infoDescription': 'Provide detailed and accurate information about your brand to help our AI generate better, more engaging content for your social media posts.',
      'brandSetup.updateTitle': 'Update Brand Profile',
      'brandSetup.completeTitle': 'Complete Brand Profile',
      'brandSetup.updateDescription': 'Update your brand information',
      'brandSetup.completeDescription': 'Tell us about your brand to get started',
      'brandSetup.brandName': 'Brand Name',
      'brandSetup.brandNamePlaceholder': 'Enter your brand name',
      'brandSetup.brandLocation': 'Brand Location',
      'brandSetup.selectLocations': 'Select locations',
      'brandSetup.specifyLocation': 'Specify your location',
      'brandSetup.brandType': 'Brand Type',
      'brandSetup.selectBrandType': 'Select brand type',
      'brandSetup.customBrandType': 'Please write your Brand type',
      'brandSetup.enterBrandType': 'Enter your brand type',
      'brandSetup.category': 'Category',
      'brandSetup.selectCategory': 'Select category',
      'brandSetup.customCategory': 'Please write your restaurant category',
      'brandSetup.enterCategory': 'Enter your restaurant category',
      'brandSetup.brandVision': 'Brand Vision and Value',
      'brandSetup.visionPlaceholder': 'Describe your brand\'s vision, mission, and core values. What makes your brand unique? What do you stand for?',
      'brandSetup.cancel': 'Cancel',
      'brandSetup.updating': 'Updating...',
      'brandSetup.creating': 'Creating...',
      'brandSetup.updateBrand': 'Update Brand',
      'brandSetup.completeSetup': 'Complete Setup',
      'brandSetup.success': 'Success',
      'brandSetup.updateSuccess': 'Brand profile updated successfully',
      'brandSetup.createSuccess': 'Brand profile created successfully',
      'brandSetup.error': 'Error',
      'brandSetup.saveError': 'Failed to save brand information',
      
      // Media Management
      'media.title': 'Media Management',
      'media.description': 'Manage your uploaded photos and product images',
      'media.addProducts': 'Add Products',
      'media.selectAll': 'Select All Products',
      'media.cancelSelection': 'Cancel Selection',
      'media.deleteSelected': 'Delete Selected ({count})',
      'media.deleteAll': 'Delete All Products',
      'media.noMedia': 'No media uploaded yet',
      'media.noFilter': 'No {filter} found',
      'media.viewGrid': 'Grid View',
      'media.viewList': 'List View',
      'media.filterAll': 'All',
      'media.filterImages': 'Images',
      'media.filterProducts': 'Products',
      'media.filterWithCaptions': 'With Captions',
      'media.filterWithoutCaptions': 'Without Captions',
      'media.deleteProducts': 'Delete Products',

      // Generated Captions
      'captions.title': 'Generated Captions',
      'captions.description': 'Manage your AI-generated captions for images and products',
      'captions.regenerate': 'Regenerate caption',
      'captions.noCredits': 'No caption credits remaining',
      'captions.generating': 'Generating...',
      'captions.generated': 'Caption generated successfully',
      'captions.failed': 'Failed to generate caption',
      'captions.noContent': 'No content yet',
      'captions.addProducts': 'Add some products with images to generate AI captions',
      'captions.addFirst': 'Add Your First Product',
      'captions.addMore': 'Add More Content',
      'captions.schedule': 'Schedule',

      // Table Headers
      'table.content': 'Content',
      'table.caption': 'Caption',
      'table.details': 'Details',
      'table.status': 'Status',
      'table.performance': 'Performance',
      'table.actions': 'Actions',

      // Authentication
      'auth.welcomeBack': 'Welcome Back',
      'auth.signInToAccount': 'Sign in to your ThinkPost account',
      'auth.emailConfirmationRequired': 'Email confirmation required:',
      'auth.checkEmailConfirmation': 'Please check your email inbox and click the confirmation link. If you don\'t see the email, check your spam folder.',
      'auth.invalidCredentials': 'Invalid email or password. Please check your credentials and try again.',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.enterEmail': 'Enter your email',
      'auth.enterPassword': 'Enter your password',
      'auth.forgotPassword': 'Forgot password?',
      'auth.signIn': 'Sign In',
      'auth.signingIn': 'Signing In...',
      'auth.signUp': 'Sign Up',
      'auth.dontHaveAccount': 'Don\'t have an account?',
      'auth.alreadyHaveAccount': 'Already have an account?',
      'auth.joinThinkPost': 'Join ThinkPost',
      'auth.createAccountToStart': 'Create your account to get started',
      'auth.fullName': 'Full Name',
      'auth.enterFullName': 'Enter your full name',
      'auth.createStrongPassword': 'Create a strong password',
      'auth.confirmPassword': 'Confirm Password',
      'auth.confirmYourPassword': 'Confirm your password',
      'auth.agreeToTerms': 'By signing up, you agree to our',
      'auth.termsOfService': 'Terms of Service',
      'auth.and': 'and',
      'auth.privacyPolicy': 'Privacy Policy',
      'auth.createAccount': 'Create Account',
      'auth.creatingAccount': 'Creating Account...',

      // Account Settings
      'accountSettings.title': 'Account Settings',
      'accountSettings.description': 'Manage your account preferences and security settings',
      'accountSettings.back': 'Back',
      'accountSettings.currentAccount': 'Current Account',
      'accountSettings.emailAddress': 'Email Address',
      'accountSettings.changeEmail': 'Change Email Address',
      'accountSettings.changeEmailDescription': 'Update your email address. You\'ll need to confirm both your old and new email addresses.',
      'accountSettings.newEmailAddress': 'New Email Address',
      'accountSettings.enterNewEmail': 'Enter your new email address',
      'accountSettings.updateEmail': 'Update Email',
      'accountSettings.updating': 'Updating...',
      'accountSettings.emailUpdateRequested': 'Email Update Requested',
      'accountSettings.emailUpdateDescription': 'Please check both your old and new email addresses for confirmation links.',
      'accountSettings.changePassword': 'Change Password',
      'accountSettings.changePasswordDescription': 'Update your password to keep your account secure.',
      'accountSettings.newPassword': 'New Password',
      'accountSettings.enterNewPassword': 'Enter your new password',
      'accountSettings.confirmNewPassword': 'Confirm New Password',
      'accountSettings.confirmNewPasswordPlaceholder': 'Confirm your new password',
      'accountSettings.updatePassword': 'Update Password',
      'accountSettings.passwordsDoNotMatch': 'New passwords do not match',
      'accountSettings.passwordTooShort': 'Password must be at least 6 characters long',
      'accountSettings.passwordUpdated': 'Password updated successfully',
      'accountSettings.dangerZone': 'Danger Zone',
      'accountSettings.dangerZoneDescription': 'Permanently delete your account and all associated data. This action cannot be undone.',
      'accountSettings.deleteAccount': 'Delete Account',
      'accountSettings.deleteConfirmTitle': 'Are you absolutely sure?',
      'accountSettings.deleteConfirmDescription': 'This action cannot be undone. This will permanently delete your account and remove all your data from our servers.',
      'accountSettings.deleteConfirmInstructions': 'To confirm, type DELETE in the box below:',
      'accountSettings.deleteConfirmPlaceholder': 'Type DELETE to confirm',
      'accountSettings.cancel': 'Cancel',
      'accountSettings.deleting': 'Deleting...',
      'accountSettings.deleteConfirmationError': 'Please type \'DELETE\' to confirm account deletion',
      'accountSettings.accountDeleted': 'Account Deleted',
      'accountSettings.accountDeletedDescription': 'Your account has been permanently deleted. You can register again with the same email if needed.',
      'accountSettings.error': 'Error',
      'accountSettings.success': 'Success',
      'accountSettings.failedToUpdateEmail': 'Failed to update email',
      'accountSettings.failedToUpdatePassword': 'Failed to update password',
      'accountSettings.failedToDeleteAccount': 'Failed to delete account',

      // Restaurant Setup
      'restaurant.updateProfile': 'Update Business Profile',
      'restaurant.completeProfile': 'Complete Your Business Profile',
      'restaurant.updateInformation': 'Update your business information',
      'restaurant.tellUsAbout': 'Tell us about your business to get started with ThinkPost',
      'restaurant.name': 'Business Name',
      'restaurant.enterName': 'Enter your business name',
      'restaurant.location': 'Location',
      'restaurant.locationPlaceholder': 'Select your region',
      'restaurant.category': 'Category',
      'restaurant.selectCategory': 'Select business category',
      'restaurant.vision': 'Business Vision',
      'restaurant.visionPlaceholder': 'Describe your business\'s vision, style, and what makes it special...',
      'restaurant.cancel': 'Cancel',
      'restaurant.updating': 'Updating...',
      'restaurant.creating': 'Creating...',
      'restaurant.updateButton': 'Update Profile',
      'restaurant.completeSetup': 'Complete Setup',
      'restaurant.success': 'Success!',
      'restaurant.profileUpdated': 'Business profile updated successfully',
      'restaurant.profileCreated': 'Business profile created successfully',
      'restaurant.error': 'Error',
      'restaurant.failedToLoad': 'Failed to load business data',
      'restaurant.failedToSave': 'Failed to save business profile',

      // Scheduled Posts
      'schedule.title': 'Scheduled Posts',
      'schedule.description': 'Schedule and manage your social media posts',
      'schedule.schedulePosts': 'Schedule Posts',
      'schedule.noPosts': 'No posts scheduled for this date',
      'schedule.deleteAll': 'Delete All Scheduled Tasks',
      'schedule.editDate': 'Edit Date',
      'schedule.delete': 'Delete',
      'schedule.cancel': 'Cancel',
      'schedule.needContent': 'You need products or images with captions to schedule posts',
      'schedule.dailyView': 'Daily View',
      'schedule.weeklyView': 'Weekly View',
      'schedule.calendar': 'Calendar',
      'schedule.reviewedAndSubmitted': 'Reviewed and Submitted',
      'schedule.cancelScheduledPostsAndEdits': 'Cancel Scheduled Posts and Edits',
      'schedule.preferences.title': 'Scheduling Preferences',
      'schedule.preferences.description': 'Configure how you want your posts to be scheduled',
      'schedule.preferences.days': 'Scheduling Days',
      'schedule.preferences.times': 'Posting Times',
      'schedule.preferences.confirm': 'Schedule Posts',
      'schedule.preferences.cancel': 'Cancel',
      'schedule.preferences.days.2weekly': '2 days weekly',
      'schedule.preferences.days.4weekly': '4 days weekly',
      'schedule.preferences.days.daily': 'Daily',
      'schedule.preferences.days.custom': 'Custom',
      'schedule.preferences.days.everyX': 'Every X days',
      'schedule.preferences.times.morning': 'Morning period (7-9 AM)',
      'schedule.preferences.times.lunch': 'Lunch period (12-2 PM)',
      'schedule.preferences.times.evening': 'Evening period (4-6 PM)',
      'schedule.preferences.times.night': 'Night period (7-11 PM)',
      'schedule.preferences.times.random': 'Random (mix of all periods)',
      'schedule.preferences.customDays.monday': 'Monday',
      'schedule.preferences.customDays.tuesday': 'Tuesday',
      'schedule.preferences.customDays.wednesday': 'Wednesday',
      'schedule.preferences.customDays.thursday': 'Thursday',
      'schedule.preferences.customDays.friday': 'Friday',
      'schedule.preferences.customDays.saturday': 'Saturday',
      'schedule.preferences.customDays.sunday': 'Sunday',
      'schedule.preferences.everyXDays': 'Every {x} days',

      // Notifications
      'notifications.title': 'Notifications',
      'notifications.description': 'Choose what notifications you want to receive',
      'notifications.noNotifications': 'No notifications yet',
      'notifications.markAsRead': 'Mark as read',
      'notifications.delete': 'Delete',
      'notifications.captionGenerated': 'Caption Generated',
      'notifications.uploadFailed': 'Upload Failed',
      'notifications.uploadStatus': 'Upload Status',
      'notifications.captionSettings': 'Get notified when AI captions are generated',

      // Image Upload Page
      'upload.backToDashboard': 'Back to Dashboard',
      'upload.title': 'Upload Images',
      'upload.description': 'Upload photos of your delicious dishes to generate AI-powered captions',
      'upload.selectImages': 'Select Images',
      'upload.selectImagesDescription': 'Choose multiple images to upload. Supported formats: JPG, PNG, WEBP',
      'upload.clickToUpload': 'Click to upload images',
      'upload.dragAndDrop': 'or drag and drop your files here',
      'upload.selectedImages': 'Selected Images',
      'upload.uploadButton': 'Upload {count} Image(s)',
      'upload.uploading': 'Uploading...',
      'upload.clearAll': 'Clear All',
      'upload.uploadSuccess': 'Success!',
      'upload.uploadSuccessDescription': '{count} image(s) uploaded successfully',
      'upload.uploadFailed': 'Upload Failed',
      'upload.uploadFailedDescription': 'Failed to upload images',
      'upload.addProducts': 'Add Products',
      'upload.addProductsDescription': 'Add your delicious dishes with details and images to generate AI-powered captions',
      'upload.productsSavedOnly': '{count} product(s) saved successfully',
      'upload.productsSavedWithCaptions': '{count} product(s) saved and captions generated successfully',
      
      // Product Creation Page
      'productCreation.platformConnectionStatus': 'Platform Connection Status',
      'productCreation.currentConnections': 'Current platform connections for posting',
      'productCreation.tiktokName': 'TikTok Name:',
      'productCreation.loading': 'Loading...',
      'productCreation.tiktokUser': 'TikTok User',
      'productCreation.notConnected': 'Not connected',
      'productCreation.connectedAs': 'Connected as @{username}',
      
      // Product Card
      'productCard.product': 'Product {number}',
      'productCard.productName': 'Product Name',
      'productCard.productNameRequired': 'Product Name *',
      'productCard.productNamePlaceholder': 'e.g., Margherita Pizza',
      'productCard.price': 'Price ($)',
      'productCard.pricePlaceholder': 'e.g., 12.99 (optional)',
      'productCard.description': 'Description',
      'productCard.descriptionPlaceholder': 'Describe your product... (optional)',
      'productCard.productImage': 'Product Image',
      'productCard.productImageRequired': 'Product Image *',
      'productCard.clickToUpload': 'Click to upload image',
      'productCard.productPreview': 'Product preview',
      'productCard.platforms': 'Platforms',
      'productCard.selectPlatforms': 'Select platforms to post this product to',
      'productCard.tiktokSettings': 'TikTok Settings',
      'productCard.privacyLevel': 'Privacy Level',
      'productCard.public': 'Public',
      'productCard.friends': 'Friends',
      'productCard.onlyMe': 'Only Me',
      'productCard.allowComments': 'Allow Comments',
      'productCard.allowDuet': 'Allow Duet',
      'productCard.allowStitch': 'Allow Stitch',
      'productCard.commercialContent': 'Commercial Content',
      'productCard.yourBrand': 'Your Brand',
      'productCard.brandedContent': 'Branded Content',
      'productCard.complianceInfo': 'By posting, you agree to TikTok\'s policies',
      'productCard.advancedSettings': 'Advanced Settings',
      'productCard.postToTikTok': 'Post to TikTok',
      'productCard.connectTikTokFirst': 'Connect TikTok account first',
      'productCard.privacyLevelLabel': 'Privacy Level:',
      'productCard.interactionSettings': 'Interaction Settings',
      'productCard.commercialContentLabel': 'This content promotes a brand, product or service',
      'productCard.validationWarning': '⚠️ You need to indicate if your content promotes yourself, a third party, or both.',
      
      // Product Actions
      'productActions.addAnother': 'Add Another Product',
      'productActions.save': 'Save',
      'productActions.saving': 'Saving...',
      'productActions.saveAndGenerate': 'Save & Generate Captions',
      'productActions.uploadingGenerating': 'Uploading & Generating Content...',
    },
    ar: {
      // Header
      'nav.features': 'المميزات',
      'nav.howItWorks': 'كيف تستخدم منصتنا',
      'nav.pricing': 'الأسعار',
      'nav.contact': 'اتصل بنا',
      'header.getStarted': 'ابدأ الآن',
      'header.signOut': 'تسجيل الخروج',
      'header.welcomeBack': 'أهلاً بعودتك!',
      
      // Hero
      'hero.badge': 'إنتاج محتوى بالذكاء الاصطناعي',
      'hero.title.transform': 'الذكاء الاصطناعي يشيل عنك هم التسويق والانتشار وأنت ركز على شغفك',
      'hero.title.contentStrategy': 'ارفع منتجاتك، واحصل على محتوى تسويقي ذكي وجدول منشوراتك تلقائيًا  على مواقع التواصل — بسهولة، وبدون صداع المحتوى.',
      'hero.subtitle': 'منصة تسويقية ذكية للمطاعم والكافيهات وغيرها، تولّد لك محتوى متناسق مع هوية مشروعك، وتجدوله وتنزله في السوشال ميديا – كل هذا بثواني!',
      'hero.description': 'أنشئ محتوى جذاب وعالي الجودة مع منصتنا المتخصصة في إنشاء المحتوى وجدولته ونشره في منصات التواصل الاجتماعي. عزز إنتاجيتك وبأفكار متجددة وكثيرة وبأسلوب يعكس هويتك.',
      'hero.startCreating': 'ابدأ مجاناً',
      'hero.watchDemo': 'شاهد العرض التوضيحي',
      'hero.goToDashboard': 'اذهب إلى لوحة التحكم',
      'hero.loading': 'جارٍ التحميل...',
      'hero.demoTitle': 'فيديو العرض التوضيحي قريباً',
      'hero.demoDescription': 'شاهد نموذج العمل',
      
      // Features
      'features.title.powerful': 'مميزات رهيبة',
      'features.title.creators': 'لمن يريد إنشاء محتوى',
      'features.description': 'منصتنا هي ذراعك القوي لأتمتة التسويق في منصات السوشال ميديا باستخدام الذكاء الاصطناعي',
      'features.feature1.title': 'توليد مدعوم بالذكاء الاصطناعي',
      'features.feature1.description': 'محتوى مخصص لصوت علامتك التجارية وأسلوبك',
      'features.feature2.title': 'سرعة البرق',
      'features.feature2.description': 'انتج محتوى عالي الجودة في ثوانٍ وليس ساعات. عزز إنتاجيتك.',
      'features.feature3.title': 'محتوى مستهدف',
      'features.feature3.description': 'أنشئ محتوى محسّن لجمهورك المحدد وأهدافك التسويقية.',
      'features.feature4.title': 'مراجعة المنشورات قبل النشر',
      'features.feature4.description': 'بعد توليد المحتوى من الذكاء الاصطناعي، يمكنك تعديل عليه حسب رغبتك.',
      'features.feature5.title': 'متعدد اللغات',
      'features.feature5.description': 'ندعم أيضا إنشاء المحتوى بأي لغة ترغب فيها.',
      'features.feature6.title': 'خوارزميات تجدول لك منشوراتك للفترة القادمة',
      'features.feature6.description': 'منصتنا تمسك عنك جدولة المنشورات بعد، وأيضا يمكنك بنفسك تعديل وتختار الأيام والوقت اللي تبي منشوراتك تنزل فيه.',
      
      // How It Works
      'howItWorks.title': 'كيف تستخدم منصتنا؟',
      'howItWorks.description': 'ابدأ مع ThinkPost في ثلاث خطوات بسيطة وحوّل عملية إنشاء المحتوى الخاصة بك.',
      'howItWorks.step1.title': 'ارفع منتجاتك',
      'howItWorks.step1.description': 'أضف صورة المنتج والاسم برفع بسيط.',
      'howItWorks.step2.title': 'الذكاء الاصطناعي ينتج المحتوى',
      'howItWorks.step2.description': 'ذكاؤنا الاصطناعي ينتج محتوى ملائم لثقافة مشروعك وبلهجة سعودية بأسلوب عالي الجودة وجذاب.',
      'howItWorks.step3.title': 'راجع وانشر',
      'howItWorks.step3.description': 'راجع المحتوى المُنتج، قم بأي تعديلات، ثم جدول وانشر عبر قنواتك.',
      'howItWorks.startTrial': 'ابدأ تجربتك المجانية',

      // Pricing
      'pricing.title': 'الأسعار',
      'pricing.subtitle': 'اختر الخطة المثالية لعملك. جميع الخطط تشمل ميزات الذكاء الاصطناعي الأساسية.',
      'pricing.mostPopular': 'الأكثر شعبية',
      'pricing.plans.free.name': 'مجاني',
      'pricing.plans.free.period': '/شهر',
      'pricing.plans.free.description': 'مثالي للبداية',
      'pricing.plans.free.features.posts': '١٤ منشور شهرياً',
      'pricing.plans.free.features.captions': 'تسميات توضيحية أساسية بالذكاء الاصطناعي',
      'pricing.plans.free.features.platforms': 'منصتان اجتماعيتان',
      'pricing.plans.free.features.support': 'دعم قياسي',
      'pricing.plans.free.features.templates': 'قوالب أساسية',
      'pricing.plans.free.buttonText': 'ابدأ مجاناً',
      'pricing.plans.pro.name': 'احترافي',
      'pricing.plans.pro.period': '/شهر',
      'pricing.plans.pro.description': 'الأفضل للشركات النامية',
      'pricing.plans.pro.features.posts': '100 منشور شهرياً',
      'pricing.plans.pro.features.captions': 'تسميات توضيحية متقدمة بالذكاء الاصطناعي',
      'pricing.plans.pro.features.platforms': 'جميع المنصات الاجتماعية',
      'pricing.plans.pro.features.support': 'دعم ذو أولوية',
      'pricing.plans.pro.features.templates': 'قوالب مخصصة',
      'pricing.plans.pro.features.analytics': 'لوحة تحليلات',
      'pricing.plans.pro.features.scheduling': 'أدوات الجدولة',
      'pricing.plans.pro.features.arabic': 'دعم اللهجة السعودية',
      'pricing.plans.pro.buttonText': 'ابدأ الاحترافي',
      'pricing.plans.business.name': 'تجاري',
      'pricing.plans.business.period': '/شهر',
      'pricing.plans.business.description': 'للفرق الكبيرة والوكالات',
      'pricing.plans.business.features.posts': 'منشورات غير محدودة',
      'pricing.plans.business.features.captions': 'تسميات توضيحية مميزة بالذكاء الاصطناعي',
      'pricing.plans.business.features.platforms': 'جميع المنصات الاجتماعية',
      'pricing.plans.business.features.support': 'دعم مخصص على مدار الساعة',
      'pricing.plans.business.features.branding': 'علامة تجارية مخصصة',
      'pricing.plans.business.features.analytics': 'تحليلات متقدمة',
      'pricing.plans.business.features.collaboration': 'تعاون الفريق',
      'pricing.plans.business.features.api': 'وصول API',
      'pricing.plans.business.features.whiteLabel': 'حل العلامة البيضاء',
      'pricing.plans.business.features.integrations': 'تكاملات مخصصة',
      'pricing.plans.business.buttonText': 'ابدأ التجاري',
      'pricing.enterprise.title': 'تحتاج شيئاً مخصصاً؟',
      'pricing.enterprise.description': 'لعملاء المؤسسات ذوي المتطلبات الخاصة، نقدم حلول مخصصة ودعماً مخصصاً.',
      'pricing.enterprise.buttonText': 'اتصل بالمبيعات',

      // FAQ
      'faq.title': 'الأسئلة الشائعة',
      'faq.subtitle': 'كل ما تحتاج لمعرفته عن ThinkPost',
      'faq.questions.q1.question': 'كيف ينتج ThinkPost التسميات التوضيحية؟',
      'faq.questions.q1.answer': 'ذكاؤنا الاصطناعي المتقدم يحلل محتواك، يفهم السياق، وينتج تسميات توضيحية جذابة مخصصة لكل منصة تواصل اجتماعي. يأخذ في الاعتبار عوامل مثل الجمهور والنبرة والهاشتاجات الرائجة وأفضل ممارسات كل منصة.',
      'faq.questions.q2.question': 'ما هي منصات التواصل الاجتماعي المدعومة؟',
      'faq.questions.q2.answer': 'حاليا ندعم منصة TikTok فقط. مع العمل على توسيع الدعم لمنصات أخرى في المستقبل.',
      'faq.questions.q3.question': 'هل يمكنني تخصيص وتعديل المحتوى المولد؟',
      'faq.questions.q3.answer': 'بالطبع! منصتنا توفر نقطة بداية رائعة، لكن لديك القدرة الكاملة لتحرير أو تعديل أو إعادة كتابة أي محتوى منتج بالكامل. يمكنك أيضاً تعيين تفضيلات للنبرة والأسلوب وكلمات مفتاحية محددة.',
      'faq.questions.q4.question': 'ما مدى دقة دعم اللهجة العربية؟',
      'faq.questions.q4.answer': 'ذكاؤنا الاصطناعي مدرب على اللهجات العربية السعودية والفروق الثقافية. يفهم التعبيرات المحلية والمراجع الثقافية وينشئ محتوى أصيل يتردد صداه مع الجماهير الناطقة بالعربية.',
      'faq.questions.q5.question': 'هل هناك تجربة مجانية متاحة؟',
      'faq.questions.q5.answer': 'نعم! خطتنا المجانية تشمل ١٤ منشور شهرياً مع تسميات توضيحية أساسية بالذكاء الاصطناعي لمنصتين اجتماعيتين. يمكنك الترقية في أي وقت للوصول إلى المزيد من الميزات والحدود الأعلى.',
      'faq.questions.q6.question': 'هل يمكنني جدولة المنشورات لوقت لاحق؟',
      'faq.questions.q6.answer': 'نعم، مع خططنا الاحترافية والتجارية، تحصل على الوصول إلى أدوات الجدولة لدينا. يمكنك التخطيط لتقويم المحتوى الخاص بك ونشر المنشورات تلقائياً في الأوقات المثلى لأقصى التفاعل.',
      'faq.questions.q7.question': 'ما هي تنسيقات الملفات التي ندعمها؟',
      'faq.questions.q7.answer': 'ندعم جميع تنسيقات الصور الرئيسية (JPG، PNG، GIF، WebP). نظامنا يحسن محتواك تلقائياً لمتطلبات كل منصة.',
      'faq.questions.q8.question': 'ما مدى أمان محتواي؟',
      'faq.questions.q8.answer': 'نأخذ الأمان على محمل الجد. جميع التحميلات مشفرة، ولا نخزن محتواك أطول من اللازم.',
      'faq.contact.title': 'لا تزال لديك أسئلة؟',
      'faq.contact.description': 'فريق الدعم لدينا هنا لمساعدتك في الحصول على أقصى الاستفادة من ThinkPost',
      'faq.contact.buttonText': 'اتصل بالدعم',

      // Footer
      'footer.newsletter.title': 'ابق محدثاً مع ThinkPost',
      'footer.newsletter.description': 'احصل على آخر التحديثات والنصائح واستراتيجيات إنشاء المحتوى الحصرية في صندوق الوارد الخاص بك.',
      'footer.newsletter.placeholder': 'أدخل بريدك الإلكتروني',
      'footer.newsletter.buttonText': 'اشترك',
      'footer.description': 'نحدث ثورة في إنشاء المحتوى بأدوات مدعومة بالذكاء الاصطناعي تساعدك على إنشاء محتوى جذاب وعالي الجودة في ثوانٍ.',
      'footer.sections.product': 'المنتج',
      'footer.sections.company': 'الشركة',
      'footer.sections.support': 'الدعم',
      'footer.sections.legal': 'قانوني',
      'footer.product.features': 'المميزات',
      'footer.product.pricing': 'الأسعار',
      'footer.product.api': 'واجهة برمجة التطبيقات',
      'footer.product.documentation': 'التوثيق',
      'footer.company.about': 'من نحن',
      'footer.company.careers': 'الوظائف',
      'footer.company.press': 'الصحافة',
      'footer.company.contact': 'اتصل بنا',
      'footer.support.helpCenter': 'مركز المساعدة',
      'footer.support.community': 'المجتمع',
      'footer.support.status': 'الحالة',
      'footer.support.security': 'الأمان',
      'footer.legal.privacy': 'سياسة الخصوصية',
      'footer.legal.terms': 'شروط الخدمة',
      'footer.legal.cookies': 'سياسة ملفات تعريف الارتباط',
      'footer.legal.gdpr': 'اللائحة العامة لحماية البيانات',
      'footer.copyright': '© 2024 ThinkPost. جميع الحقوق محفوظة.',
      'footer.bottomLinks.privacy': 'الخصوصية',
      'footer.bottomLinks.terms': 'الشروط',
      'footer.bottomLinks.cookies': 'ملفات تعريف الارتباط',
      
      // Dashboard
      'dashboard.loading': 'جارٍ تحميل لوحة التحكم...',
      'dashboard.tabs.overview': 'نظرة عامة',
      'dashboard.tabs.media': 'الوسائط',
      'dashboard.tabs.captions': 'توليد المحتوى',
      'dashboard.tabs.schedule': 'الجدولة',
      'dashboard.tabs.statistics': 'الإحصائيات',
      
      // Overview Cards
      'dashboard.overview.totalPosts': 'إجمالي المنشورات',
      'dashboard.overview.totalPostsSubtext': '+12% من الشهر الماضي',
      'dashboard.overview.upcomingPosts': 'المنشورات القادمة',
      'dashboard.overview.upcomingPostsSubtext': 'مجدولة هذا الأسبوع',
      'dashboard.overview.captionCredits': 'رصيد توليد المحتوى',
      'dashboard.overview.captionCreditsSubtext': '{credits} رصيد متبقي',
      'dashboard.overview.mediaLibrary': 'مكتبة الوسائط',
      'dashboard.overview.mediaLibrarySubtext': 'صور مرفوعة',
      
      // Quick Actions
      'dashboard.quickActions.title': 'إجراءات سريعة',
      'dashboard.quickActions.addProducts': 'ابدأ وأضف منتجات',
      'dashboard.quickActions.viewCaptions': 'عرض المحتويات التي تم توليدها',
      'dashboard.quickActions.schedulePost': 'جدولة المنشورات',
      'dashboard.quickActions.workflow': 'الطريقة باختصار: إضافة المنتجات ← توليد المنشورات ← جدولة المنشورات',
      
      // TikTok Connection
      'dashboard.tiktok.title': 'اتصال TikTok',
      'dashboard.tiktok.description': 'اربط حساب تيك توك الخاص بك لجدولة ونشر المحتوى مباشرة',
      'dashboard.tiktok.connectedAs': 'متصل باسم @{username}',
      'dashboard.tiktok.connectedStatus': 'متصل بـ TikTok',
      'dashboard.tiktok.disconnect': 'قطع الاتصال مع TikTok',
      'dashboard.tiktok.connectDescription': 'اربط حسابك في TikTok للوصول إلى ميزات إضافية وتحسين إنشاء المحتوى.',
      'dashboard.tiktok.connecting': 'جارٍ الاتصال...',
      'dashboard.tiktok.connect': 'اربط TikTok',
      'dashboard.tiktok.readyToConnect': 'جاهز للاتصال',
      
      // Instagram Connection
      'dashboard.instagram.title': 'Instagram Business',
      'dashboard.instagram.description': 'اربط حساب Instagram Business الخاص بك لجدولة ونشر المحتوى مباشرة',
      'dashboard.instagram.connectedAs': 'متصل باسم @{username}',
      'dashboard.instagram.connectedStatus': 'متصل',
      'dashboard.instagram.disconnect': 'قطع الاتصال',
      'dashboard.instagram.connectDescription': 'اربط حساب Instagram Business للوصول إلى ميزات إضافية وتحسين إنشاء المحتوى.',
      'dashboard.instagram.connecting': 'جارٍ الاتصال...',
      'dashboard.instagram.connect': 'اربط Instagram Business',
      'dashboard.instagram.readyToConnect': 'جاهز للاتصال',
      
      // User Profile
      'dashboard.profile.owner': 'المالك',
      'dashboard.profile.ownerOf': 'مالك {name}',
      'dashboard.profile.profileSettings': 'إعدادات الملف الشخصي',
      'dashboard.profile.accountSettings': 'إعدادات الحساب',
      'dashboard.profile.signOut': 'تسجيل الخروج',

      // Profile Settings
      'profileSettings.title': 'إعدادات الملف الشخصي',
      'profileSettings.description': 'تحديث معلوماتك الشخصية والتجارية',
      'profileSettings.personalInfo.title': 'المعلومات الشخصية',
      'profileSettings.personalInfo.description': 'إدارة تفاصيل حسابك الشخصي',
      'profileSettings.brandInfo.title': 'معلومات العلامة التجارية',
      'profileSettings.brandInfo.description': 'تحديث تفاصيل منشأتك ورؤيتها',

      // Profile Form
      'profileForm.avatarUrl': 'رابط الصورة الشخصية',
      'profileForm.avatarUrlPlaceholder': 'https://example.com/avatar.jpg',
      'profileForm.email': 'البريد الإلكتروني',
      'profileForm.fullName': 'الاسم الكامل',
      'profileForm.fullNamePlaceholder': 'أدخل اسمك الكامل',
      'profileForm.displayName': 'اسم العرض',
      'profileForm.displayNamePlaceholder': 'أدخل اسم العرض',
      'profileForm.updateProfile': 'تحديث الملف الشخصي',
      'profileForm.updating': 'جارٍ التحديث...',
      'profileForm.success': 'تم تحديث الملف الشخصي',
      'profileForm.successDescription': 'تم تحديث معلومات ملفك الشخصي بنجاح.',
      'profileForm.error': 'خطأ',
      'profileForm.errorDescription': 'فشل في تحديث معلومات الملف الشخصي.',

      // Restaurant Form
      'restaurantForm.specifyLocation': 'حدد موقعك',
      'restaurantForm.brandType': 'نوع العلامة التجارية',
      'restaurantForm.selectBrandType': 'اختر نوع العلامة التجارية',
      'restaurantForm.customBrandType': 'يرجى كتابة نوع علامتك التجارية',
      'restaurantForm.enterBrandType': 'أدخل نوع علامتك التجارية',
      'restaurantForm.customCategory': 'يرجى كتابة فئة منشأتك',
      'restaurantForm.enterCategory': 'أدخل فئة منشأتك',

      // Brand Types
      'brandTypes.restaurant': 'مطعم',
      'brandTypes.coffee': 'مقهى',
      'brandTypes.bakery': 'مخبز',
      'brandTypes.other': 'أخرى',

      // Categories
      'categories.fastFood': 'وجبات سريعة',
      'categories.casualDining': 'مطعم عادي',
      'categories.fineDining': 'مطعم راقي',
      'categories.middleEastern': 'شرق أوسطي',
      'categories.asian': 'آسيوي',
      'categories.italian': 'إيطالي',
      'categories.american': 'أمريكي',
      'categories.mexican': 'مكسيكي',
      'categories.indian': 'هندي',
      'categories.seafood': 'مأكولات بحرية',
      'categories.pizza': 'بيتزا',
      'categories.coffeeShop': 'مقهى',
      'categories.bakery': 'مخبز',
      'categories.other': 'أخرى',

      // TikTok Connection
      'tiktok.processing': 'جارٍ معالجة اتصال TikTok...',
      'tiktok.pleaseWait': 'يرجى الانتظار بينما نكمل تسجيل دخولك إلى TikTok.',
      'tiktok.connected': 'تم ربط TikTok!',
      'tiktok.connectedDescription': 'تم ربط حساب TikTok الخاص بك بنجاح.',
      'tiktok.connectedSuccessfully': 'تم ربط TikTok بنجاح!',
      'tiktok.connectionFailed': 'فشل في ربط TikTok',
      'tiktok.connectionError': 'حدث خطأ أثناء ربط حساب TikTok الخاص بك.',
      'tiktok.redirecting': 'جارٍ إعادة التوجيه إلى لوحة التحكم...',
      'tiktok.errors.general': 'حدث خطأ أثناء ربط حساب TikTok الخاص بك.',
      'tiktok.errors.missingParameters': 'معاملات مطلوبة مفقودة من TikTok.',
      'tiktok.errors.invalidState': 'حالة تفويض غير صالحة أو منتهية الصلاحية.',
      'tiktok.errors.tokenExchangeFailed': 'فشل في تبديل رمز التفويض برمز الوصول.',
      'tiktok.errors.invalidTokenResponse': 'استجابة غير صالحة من خدمة رموز TikTok.',
      'tiktok.errors.profileUpdateFailed': 'فشل في تحديث ملفك الشخصي بمعلومات TikTok.',
      'tiktok.errors.internalError': 'حدث خطأ داخلي أثناء عملية الربط.',

      // Brand Setup
      'brandSetup.infoTitle': 'إنشاء محتوى عالي الجودة',
      'brandSetup.infoDescription': 'قدم معلومات مفصلة ودقيقة عن علامتك التجارية لمساعدة الذكاء الاصطناعي في إنتاج محتوى أفضل وأكثر جاذبية لمنشوراتك على وسائل التواصل الاجتماعي.',
      'brandSetup.updateTitle': 'تحديث ملف العلامة التجارية',
      'brandSetup.completeTitle': 'إكمال ملف العلامة التجارية',
      'brandSetup.updateDescription': 'قم بتحديث معلومات علامتك التجارية',
      'brandSetup.completeDescription': 'أخبرنا عن علامتك التجارية للبدء',
      'brandSetup.brandName': 'اسم العلامة التجارية',
      'brandSetup.brandNamePlaceholder': 'أدخل اسم علامتك التجارية',
      'brandSetup.brandLocation': 'موقع العلامة التجارية',
      'brandSetup.selectLocations': 'اختر المواقع',
      'brandSetup.specifyLocation': 'حدد موقعك',
      'brandSetup.brandType': 'نوع العلامة التجارية',
      'brandSetup.selectBrandType': 'اختر نوع العلامة التجارية',
      'brandSetup.customBrandType': 'يرجى كتابة نوع علامتك التجارية',
      'brandSetup.enterBrandType': 'أدخل نوع علامتك التجارية',
      'brandSetup.category': 'الفئة',
      'brandSetup.selectCategory': 'اختر الفئة',
      'brandSetup.customCategory': 'يرجى كتابة فئة مطعمك',
      'brandSetup.enterCategory': 'أدخل فئة مطعمك',
      'brandSetup.brandVision': 'رؤية وقيم العلامة التجارية',
      'brandSetup.visionPlaceholder': 'صف رؤية علامتك التجارية ومهمتها وقيمها الأساسية. ما الذي يجعل علامتك التجارية فريدة  ؟',
      'brandSetup.cancel': 'إلغاء',
      'brandSetup.updating': 'جارٍ التحديث...',
      'brandSetup.creating': 'جارٍ الإنشاء...',
      'brandSetup.updateBrand': 'تحديث العلامة التجارية',
      'brandSetup.completeSetup': 'إكمال الإعداد',
      'brandSetup.success': 'نجح',
      'brandSetup.updateSuccess': 'تم تحديث ملف العلامة التجارية بنجاح',
      'brandSetup.createSuccess': 'تم إنشاء ملف العلامة التجارية بنجاح',
      'brandSetup.error': 'خطأ',
      'brandSetup.saveError': 'فشل في حفظ معلومات العلامة التجارية',
      
      // Media Management
      'media.title': 'إدارة الوسائط',
      'media.description': 'إدارة الصور والمنتجات المرفوعة',
      'media.addProducts': 'إضافة منتجات',
      'media.selectAll': 'تحديد جميع المنتجات',
      'media.cancelSelection': 'إلغاء التحديد',
      'media.deleteSelected': 'حذف المحدد ({count})',
      'media.deleteAll': 'حذف جميع المنتجات',
      'media.noMedia': 'لم يتم رفع وسائط بعد',
      'media.noFilter': 'لا توجد {filter}',
      'media.viewGrid': 'عرض الشبكة',
      'media.viewList': 'عرض القائمة',
      'media.filterAll': 'الكل',
      'media.filterImages': 'الصور',
      'media.filterProducts': 'المنتجات',
      'media.filterWithCaptions': 'مع تسميات توضيحية',
      'media.filterWithoutCaptions': 'بدون تسميات توضيحية',
      'media.deleteProducts': 'حذف المنتجات',

      // Generated Captions
      'captions.title': 'توليد المحتوى',
      'captions.description': 'إدارة المحتوى المولد بالذكاء الاصطناعي للصور والمنتجات',
      'captions.regenerate': 'إعادة توليد المحتوى',
      'captions.noCredits': 'لا توجد رصيد كافي لتوليد المحتوى',
      'captions.generating': 'جارٍ التوليد...',
      'captions.generated': 'تم توليد المحتوى بنجاح',
      'captions.failed': 'فشل في توليد المحتوى',
      'captions.noContent': 'لا يوجد محتوى بعد',
      'captions.addProducts': 'أضف منتجات مع صور لتوليد محتوى بالذكاء الاصطناعي',
      'captions.addFirst': 'أضف أول منتج',
      'captions.addMore': 'إضافة المزيد من المحتوى',
      'captions.schedule': 'جدولة',

      // Table Headers
      'table.content': 'المنتج',
      'table.caption': 'المحتوى',
      'table.details': 'التفاصيل',
      'table.status': 'الحالة',
      'table.performance': 'الأداء',
      'table.actions': 'الإجراءات',

      // Authentication
      'auth.welcomeBack': 'أهلاً بعودتك',
      'auth.signInToAccount': 'سجل دخولك إلى حساب ThinkPost',
      'auth.emailConfirmationRequired': 'تأكيد البريد الإلكتروني مطلوب:',
      'auth.checkEmailConfirmation': 'يرجى التحقق من صندوق البريد الإلكتروني والنقر على رابط التأكيد. إذا لم تجد البريد، تحقق من مجلد الرسائل غير المرغوب فيها.',
      'auth.invalidCredentials': 'بريد إلكتروني أو كلمة مرور غير صحيحة. يرجى التحقق من بياناتك والمحاولة مرة أخرى.',
      'auth.email': 'البريد الإلكتروني',
      'auth.password': 'كلمة المرور',
      'auth.enterEmail': 'أدخل بريدك الإلكتروني',
      'auth.enterPassword': 'أدخل كلمة المرور',
      'auth.forgotPassword': 'نسيت كلمة المرور؟',
      'auth.signIn': 'تسجيل الدخول',
      'auth.signingIn': 'جارٍ تسجيل الدخول...',
      'auth.signUp': 'إنشاء حساب',
      'auth.dontHaveAccount': 'ليس لديك حساب؟',
      'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'auth.joinThinkPost': 'انضم إلى ThinkPost',
      'auth.createAccountToStart': 'أنشئ حسابك للبدء',
      'auth.fullName': 'الاسم الكامل',
      'auth.enterFullName': 'أدخل اسمك الكامل',
      'auth.createStrongPassword': 'أنشئ كلمة مرور قوية',
      'auth.confirmPassword': 'تأكيد كلمة المرور',
      'auth.confirmYourPassword': 'أكد كلمة المرور',
      'auth.agreeToTerms': 'بإنشاء الحساب، فإنك توافق على',
      'auth.termsOfService': 'شروط الخدمة',
      'auth.and': 'و',
      'auth.privacyPolicy': 'سياسة الخصوصية',
      'auth.createAccount': 'إنشاء حساب',
      'auth.creatingAccount': 'جارٍ إنشاء الحساب...',

      // Account Settings
      'accountSettings.title': 'إعدادات الحساب',
      'accountSettings.description': 'إدارة التفضيلات وإعدادات الأمان',
      'accountSettings.back': 'رجوع',
      'accountSettings.currentAccount': 'الحساب الحالي',
      'accountSettings.emailAddress': 'البريد الإلكتروني',
      'accountSettings.changeEmail': 'تغيير البريد الإلكتروني',
      'accountSettings.changeEmailDescription': 'قم بتحديث عنوان بريدك الإلكتروني. ستحتاج إلى تأكيد عنواني بريدك الجديد والقديم.',
      'accountSettings.newEmailAddress': 'عنوان بريد جديد',
      'accountSettings.enterNewEmail': 'أدخل عنوان بريدك الجديد',
      'accountSettings.updateEmail': 'تحديث البريد الإلكتروني',
      'accountSettings.updating': 'جارٍ التحديث...',
      'accountSettings.emailUpdateRequested': 'طلب تحديث البريد الإلكتروني',
      'accountSettings.emailUpdateDescription': 'يرجى التحقق من عنواني بريدك القديم والجديد لروابط التأكيد.',
      'accountSettings.changePassword': 'تغيير كلمة المرور',
      'accountSettings.changePasswordDescription': 'قم بتحديث كلمة المرور لضمان أمان حسابك.',
      'accountSettings.newPassword': 'كلمة مرور جديدة',
      'accountSettings.enterNewPassword': 'أدخل كلمة المرور الجديدة',
      'accountSettings.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
      'accountSettings.confirmNewPasswordPlaceholder': 'تأكيد كلمة المرور الجديدة',
      'accountSettings.updatePassword': 'تحديث كلمة المرور',
      'accountSettings.passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
      'accountSettings.passwordTooShort': 'يجب أن تكون كلمة المرور على الأقل 6 أحرف طويلة',
      'accountSettings.passwordUpdated': 'تم تحديث كلمة المرور بنجاح',
      'accountSettings.dangerZone': 'الحذف',
      'accountSettings.dangerZoneDescription': 'حذف حسابك وكل البيانات المرتبطة به بشكل دائم. هذه العملية غير قابلة للتراجع.',
      'accountSettings.deleteAccount': 'حذف الحساب',
      'accountSettings.deleteConfirmTitle': 'هل أنت متأكد بأكمله؟',
      'accountSettings.deleteConfirmDescription': 'هذه العملية غير قابلة للتراجع. سيتم حذف حسابك وإزالة جميع بياناتك من خوادمنا بشكل دائم.',
      'accountSettings.deleteConfirmInstructions': 'لتأكيد، أدخل DELETE في المربع أدناه:',
      'accountSettings.deleteConfirmPlaceholder': 'أدخل DELETE لتأكيد حذف الحساب',
      'accountSettings.cancel': 'إلغاء',
      'accountSettings.deleting': 'جارٍ الحذف...',
      'accountSettings.deleteConfirmationError': 'يرجى إدخال \'DELETE\' لتأكيد حذف الحساب',
      'accountSettings.accountDeleted': 'تم حذف الحساب',
      'accountSettings.accountDeletedDescription': 'تم حذف حسابك بشكل دائم. يمكنك التسجيل مرة أخرى بنفس بريدك الإلكتروني إذا كان ذلك ضروري.',
      'accountSettings.error': 'خطأ',
      'accountSettings.success': 'نجاح',
      'accountSettings.failedToUpdateEmail': 'فشل تحديث عنوان البريد الإلكتروني',
      'accountSettings.failedToUpdatePassword': 'فشل تحديث كلمة المرور',
      'accountSettings.failedToDeleteAccount': 'فشل حذف الحساب',

      // Restaurant Setup
      'restaurant.updateProfile': 'تحديث ملف المنشأة',
      'restaurant.completeProfile': 'أكمل ملف منشأتك',
      'restaurant.updateInformation': 'حدث معلومات منشأتك',
      'restaurant.tellUsAbout': 'أخبرنا عن منشأتك للبدء مع ThinkPost',
      'restaurant.name': 'اسم المنشأة',
      'restaurant.enterName': 'أدخل اسم منشأتك',
      'restaurant.location': 'الموقع',
      'restaurant.locationPlaceholder': 'اختر منطقتك',
      'restaurant.category': 'الفئة',
      'restaurant.selectCategory': 'اختر فئة المنشأة',
      'restaurant.vision': 'رؤية المنشأة',
      'restaurant.visionPlaceholder': 'صف رؤية منشأتك وأسلوبها وما يميزها...',
      'restaurant.cancel': 'إلغاء',
      'restaurant.updating': 'جارٍ التحديث...',
      'restaurant.creating': 'جارٍ الإنشاء...',
      'restaurant.updateButton': 'تحديث الملف',
      'restaurant.completeSetup': 'إكمال الإعداد',
      'restaurant.success': 'نجح!',
      'restaurant.profileUpdated': 'تم تحديث ملف المنشأة بنجاح',
      'restaurant.profileCreated': 'تم إنشاء ملف المنشأة بنجاح',
      'restaurant.error': 'خطأ',
      'restaurant.failedToLoad': 'فشل في تحميل بيانات المنشأة',
      'restaurant.failedToSave': 'فشل في حفظ ملف المنشأة',

      // Scheduled Posts
      'schedule.title': 'المنشورات المجدولة',
      'schedule.description': 'جدولة وإدارة منشوراتك على وسائل التواصل الاجتماعي',
      'schedule.schedulePosts': 'جدولة المنشورات',
      'schedule.noPosts': 'لا توجد منشورات مجدولة لهذا التاريخ',
      'schedule.deleteAll': 'حذف جميع المهام المجدولة',
      'schedule.editDate': 'تعديل التاريخ',
      'schedule.delete': 'حذف',
      'schedule.cancel': 'إلغاء',
      'schedule.needContent': 'تحتاج إلى منتجات أو صور مع تسميات توضيحية لجدولة المنشورات',
      'schedule.dailyView': 'العرض اليومي',
      'schedule.weeklyView': 'العرض الأسبوعي',
      'schedule.calendar': 'التقويم',
      'schedule.reviewedAndSubmitted': 'تمت المراجعة والإرسال',
      'schedule.cancelScheduledPostsAndEdits': 'إلغاء جدولة المشاركات والتعديلات',
      'schedule.preferences.title': 'تفضيلات الجدولة',
      'schedule.preferences.description': 'اختر كيف تريد جدولة منشوراتك',
      'schedule.preferences.days': 'أيام الجدولة',
      'schedule.preferences.times': 'أوقات النشر',
      'schedule.preferences.confirm': 'جدولة المنشورات',
      'schedule.preferences.cancel': 'إلغاء',
      'schedule.preferences.days.2weekly': 'يومين أسبوعياً',
      'schedule.preferences.days.4weekly': '4 أيام أسبوعياً',
      'schedule.preferences.days.daily': 'يومياً',
      'schedule.preferences.days.custom': 'مخصص',
      'schedule.preferences.days.everyX': 'كل X أيام',
      'schedule.preferences.times.morning': 'فترة الصباح (7-9 صباحاً)',
      'schedule.preferences.times.lunch': 'فترة الغداء (12-2 ظهراً)',
      'schedule.preferences.times.evening': 'فترة المساء (4-6 مساءً)',
      'schedule.preferences.times.night': 'فترة الليل (7-11 مساءً)',
      'schedule.preferences.times.random': 'عشوائي (خليط من جميع الفترات)',
      'schedule.preferences.customDays.monday': 'الاثنين',
      'schedule.preferences.customDays.tuesday': 'الثلاثاء',
      'schedule.preferences.customDays.wednesday': 'الأربعاء',
      'schedule.preferences.customDays.thursday': 'الخميس',
      'schedule.preferences.customDays.friday': 'الجمعة',
      'schedule.preferences.customDays.saturday': 'السبت',
      'schedule.preferences.customDays.sunday': 'الأحد',
      'schedule.preferences.everyXDays': 'كل {x} أيام',

      // Notifications
      'notifications.title': 'الإشعارات',
      'notifications.description': 'اختر الإشعارات التي تريد استقبالها',
      'notifications.noNotifications': 'لا توجد إشعارات بعد',
      'notifications.markAsRead': 'تحديد كمقروء',
      'notifications.delete': 'حذف',
      'notifications.captionGenerated': 'تم توليد المحتوى',
      'notifications.uploadFailed': 'فشل الرفع',
      'notifications.uploadStatus': 'حالة الرفع',
      'notifications.captionSettings': 'احصل على إشعار عند توليد محتوى بالذكاء الاصطناعي',

      // Image Upload Page
      'upload.backToDashboard': 'العودة إلى لوحة التحكم',
      'upload.title': 'رفع الصور',
      'upload.description': 'ارفع صور أطباقك اللذيذة لإنتاج تسميات توضيحية بالذكاء الاصطناعي',
      'upload.selectImages': 'اختر الصور',
      'upload.selectImagesDescription': 'اختر عدة صور للرفع. التنسيقات المدعومة: JPG، PNG، WEBP',
      'upload.clickToUpload': 'انقر لرفع الصور',
      'upload.dragAndDrop': 'أو اسحب وأفلت ملفاتك هنا',
      'upload.selectedImages': 'الصور المختارة',
      'upload.uploadButton': 'رفع {count} صورة',
      'upload.uploading': 'جارٍ الرفع...',
      'upload.clearAll': 'مسح الكل',
      'upload.uploadSuccess': 'نجاح!',
      'upload.uploadSuccessDescription': 'تم رفع {count} صورة بنجاح',
      'upload.uploadFailed': 'فشل الرفع',
      'upload.uploadFailedDescription': 'فشل في رفع الصور',
      'upload.addProducts': 'إضافة المنتجات',
      'upload.addProductsDescription': 'أضف أطباقك اللذيذة مع التفاصيل والصور لتوليد تسميات توضيحية بالذكاء الاصطناعي',
      'upload.productsSavedOnly': 'تم حفظ {count} منتج بنجاح',
      'upload.productsSavedWithCaptions': 'تم حفظ {count} منتج وتوليد المحتوى بنجاح',
      
      // Product Creation Page
      'productCreation.platformConnectionStatus': 'حالة اتصال المنصات',
      'productCreation.currentConnections': 'اتصالات المنصات الحالية للنشر',
      'productCreation.tiktokName': 'اسم TikTok:',
      'productCreation.loading': 'جارٍ التحميل...',
      'productCreation.tiktokUser': 'مستخدم TikTok',
      'productCreation.notConnected': 'غير متصل',
      'productCreation.connectedAs': 'متصل باسم @{username}',
      
      // Product Card
      'productCard.product': 'المنتج {number}',
      'productCard.productName': 'اسم المنتج',
      'productCard.productNameRequired': 'اسم المنتج *',
      'productCard.productNamePlaceholder': 'مثال: بيتزا مارجريتا',
      'productCard.price': 'السعر (ريال)',
      'productCard.pricePlaceholder': 'مثال: 45.99 (اختياري)',
      'productCard.description': 'الوصف',
      'productCard.descriptionPlaceholder': 'صف منتجك... (اختياري)',
      'productCard.productImage': 'صورة المنتج',
      'productCard.productImageRequired': 'صورة المنتج *',
      'productCard.clickToUpload': 'انقر لرفع الصورة',
      'productCard.productPreview': 'معاينة المنتج',
      'productCard.platforms': 'المنصات',
      'productCard.selectPlatforms': 'اختر المنصات لنشر هذا المنتج عليها',
      'productCard.tiktokSettings': 'إعدادات TikTok',
      'productCard.privacyLevel': 'مستوى الخصوصية',
      'productCard.public': 'عام',
      'productCard.friends': 'الأصدقاء',
      'productCard.onlyMe': 'أنا فقط',
      'productCard.allowComments': 'السماح بالتعليقات',
      'productCard.allowDuet': 'السماح بالديو',
      'productCard.allowStitch': 'السماح بالستيتش',
      'productCard.commercialContent': 'محتوى تجاري',
      'productCard.yourBrand': 'علامتك التجارية',
      'productCard.brandedContent': 'محتوى ذو علامة تجارية',
      'productCard.complianceInfo': 'بالنشر، أنت توافق على سياسات TikTok',
      'productCard.advancedSettings': 'الإعدادات المتقدمة',
      'productCard.postToTikTok': 'النشر على TikTok',
      'productCard.connectTikTokFirst': 'اربط حساب TikTok أولاً',
      'productCard.privacyLevelLabel': 'مستوى الخصوصية:',
      'productCard.interactionSettings': 'إعدادات التفاعل',
      'productCard.commercialContentLabel': 'هذا المحتوى يروج لعلامة تجارية أو منتج أو خدمة',
      'productCard.validationWarning': '⚠️ تحتاج إلى تحديد ما إذا كان المحتوى يروج لك أو لطرف ثالث أو كليهما.',
      
      // Product Actions
      'productActions.addAnother': 'إضافة منتج آخر',
      'productActions.save': 'حفظ',
      'productActions.saving': 'جارٍ الحفظ...',
      'productActions.saveAndGenerate': 'حفظ وتوليد المحتوى',
      'productActions.uploadingGenerating': 'جارٍ الرفع وتوليد المحتوى...',
    }
  };
};
